# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "linux32" do |linux32|
    linux32.vm.box = "hansode/centos-6.7-i386"
    linux32.vm.provision :shell, path: "build-linux-centos.sh"
  end

  config.vm.define "linux64" do |linux64|
    linux64.vm.box = "hansode/centos-6.7-x86_64"
    linux64.vm.provision :shell, path: "build-linux-centos.sh"
  end

  config.vm.define "musl64" do |musl64|
    musl64.vm.box = "williamyeh/centos7-docker"
    musl64.vm.provision :shell, path: "build-linux-alpine.sh"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 4
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.no_install = true
  end

  config.vm.synced_folder "../target", "/rocksdb-build"
  config.vm.synced_folder "../..", "/rocksdb", type: "rsync"
  config.vm.boot_timeout = 1200
end
